fails:Exception.exception returns 'Exception' for message when no message given
