fails:Exception.new returns 'Exception' for message when no message given
