fails:Kernel.fail is a private method
fails:Kernel.fail raises a RuntimeError
fails:Kernel.fail instantiates the specified exception class
fails:Kernel.fail uses the specified message
